import { MULTILINGUAL_VOICE_TAG, normalizeTtsLanguage } from "./languages";

export const DEFAULT_KOKORO_MODEL_ID = "Supertone/supertonic-3";
export const DEFAULT_KOKORO_VOICE_ID = "F1";
export const KOKORO_MODEL_CARD_URL = `https://huggingface.co/${DEFAULT_KOKORO_MODEL_ID}`;
export const KOKORO_VOICE_DATASET_URL = KOKORO_MODEL_CARD_URL;

export type KokoroVoiceOption = {
  id: string;
  /** i18n key under `locales/*.json` (e.g. `voice.supertonic_sora`). */
  nameKey: string;
  gender: "Female" | "Male";
  /** Use `mul` for Supertonic multilingual voices (any TTS language). */
  languageTag: string;
  /** Short i18n line for settings card. */
  summaryKey: string;
};

export type KokoroVoiceGroup = {
  labelKey: string;
  voices: KokoroVoiceOption[];
};

/** Human-friendly display names (i18n keys). IDs stay F1…M5 for the engine. */
const FEMALE_VOICES: { id: string; nameKey: string; summaryKey: string }[] = [
  { id: "F1", nameKey: "voice.supertonic_sora", summaryKey: "voice.supertonic_summary_female" },
  { id: "F2", nameKey: "voice.supertonic_luna", summaryKey: "voice.supertonic_summary_female" },
  { id: "F3", nameKey: "voice.supertonic_mira", summaryKey: "voice.supertonic_summary_female" },
  { id: "F4", nameKey: "voice.supertonic_vera", summaryKey: "voice.supertonic_summary_female" },
  { id: "F5", nameKey: "voice.supertonic_iris", summaryKey: "voice.supertonic_summary_female" },
];

const MALE_VOICES: { id: string; nameKey: string; summaryKey: string }[] = [
  { id: "M1", nameKey: "voice.supertonic_leo", summaryKey: "voice.supertonic_summary_male" },
  { id: "M2", nameKey: "voice.supertonic_kai", summaryKey: "voice.supertonic_summary_male" },
  { id: "M3", nameKey: "voice.supertonic_rex", summaryKey: "voice.supertonic_summary_male" },
  { id: "M4", nameKey: "voice.supertonic_omar", summaryKey: "voice.supertonic_summary_male" },
  { id: "M5", nameKey: "voice.supertonic_axel", summaryKey: "voice.supertonic_summary_male" },
];

const femaleVoices: KokoroVoiceOption[] = FEMALE_VOICES.map((v) => ({
  id: v.id,
  nameKey: v.nameKey,
  gender: "Female" as const,
  languageTag: MULTILINGUAL_VOICE_TAG,
  summaryKey: v.summaryKey,
}));

const maleVoices: KokoroVoiceOption[] = MALE_VOICES.map((v) => ({
  id: v.id,
  nameKey: v.nameKey,
  gender: "Male" as const,
  languageTag: MULTILINGUAL_VOICE_TAG,
  summaryKey: v.summaryKey,
}));

export const KOKORO_VOICE_GROUPS: KokoroVoiceGroup[] = [
  { labelKey: "voice.group_female", voices: femaleVoices },
  { labelKey: "voice.group_male", voices: maleVoices },
];

const ALL_VOICE_IDS = new Set(
  KOKORO_VOICE_GROUPS.flatMap((g) => g.voices).map((v) => v.id)
);

/** Map legacy Kokoro voice ids to Supertonic styles (see `kokoros` `builtin_voice_aliases`). */
const LEGACY_VOICE_TO_SUPER: Record<string, string> = {
  af_heart: "M1",
  af_bella: "F1",
  am_adam: "M1",
  af_sarah: "F1",
};

export function normalizeVoiceId(raw: string): string {
  if (ALL_VOICE_IDS.has(raw)) return raw;
  return LEGACY_VOICE_TO_SUPER[raw] ?? "F1";
}

/**
 * Bundled preview MP3 path: one file per TTS language and voice id
 * (`resources/voice-samples/{lang}/{voiceId}.mp3`). Generated by
 * `scripts/generate_supertonic_voice_samples.sh`.
 */
export function voiceSamplePathsToTry(voiceId: string, ttsLanguage: string): string[] {
  const normalizedVoiceId = normalizeVoiceId(voiceId);
  const lang = normalizeTtsLanguage(ttsLanguage);
  const primary = `voice-samples/${lang}/${normalizedVoiceId}.mp3`;
  if (lang === "en") {
    return [primary];
  }
  return [primary, `voice-samples/en/${normalizedVoiceId}.mp3`];
}
